version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification_bot_app
    # environment:
    #   - BOT_TOKEN=${BOT_TOKEN}
    #   - DB_HOST=postgres
    #   - DB_PORT=5432
    #   - DB_USER=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_NAME=${DB_NAME}
    #   - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
    #   - MANAGER_TELEGRAM_ID=${MANAGER_TELEGRAM_ID}
    env_file:
      - .env
    volumes:
      - .:/app # Для hot-reload (может потребовать доп. настройки в Go)
    ports:
      - "8080:8080" # Если используется Gin для Webhook
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: notification_bot_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-notification_db}
    ports:
      - "${DB_PORT_HOST:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

